# Generated by Django 5.0.14 on 2026-04-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("host", models.CharField(max_length=200)),
                ("members", models.CharField(max_length=200)),
            ],
        ),
    ]
