# Generated by Django 5.0.14 on 2026-04-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forwards(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    User = apps.get_model("user", "CustomUser")

    users = list(User.objects.order_by("id"))
    if not users:
        return

    for event in Event.objects.all():
        legacy_host = getattr(event, "host_id", None)
        if isinstance(legacy_host, int):
            continue

        legacy_host_text = str(legacy_host or "").strip()
        user = (
            User.objects.filter(name=legacy_host_text).first()
            or User.objects.filter(username=legacy_host_text).first()
            or User.objects.filter(email=legacy_host_text).first()
            or users[0]
        )
        event.host_id = user.id
        event.save(update_fields=["host"])


def backwards(apps, schema_editor):
    Event = apps.get_model("events", "Event")

    for event in Event.objects.all():
        event.host_id = str(event.host_id)
        event.save(update_fields=["host"])


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RunPython(forwards, backwards),
    ]
