# Generated by Django 5.0.14 on 2026-04-29 18:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_host"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="members",
        ),
        migrations.AddField(
            model_name="event",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="events_joined", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
