# Generated by Django 6.0.4 on 2026-04-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_remove_event_members_event_members"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="members",
            new_name="member_list",
        ),
    ]
