# Generated by Django 5.0.14 on 2026-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_rename_members_event_member_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="information",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
